services:
  - type: web
    name: ultra-bot
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    pythonVersion: "3.11.8"
    envVars:
      - key: XAI_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
